# Generated by Django 5.2.7 on 2025-11-03 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_number",
                    models.CharField(
                        help_text="製品識別品番",
                        max_length=100,
                        unique=True,
                        verbose_name="製品品番",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="製品名称"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="製品詳細説明", verbose_name="製品説明"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "有効"),
                            ("DEISCONTINUED", "廃盤"),
                            ("DEVELOPMENT", "開発中"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "製品",
                "verbose_name_plural": "製品一覧",
                "db_table": "products",
                "ordering": ["product_number"],
                "indexes": [
                    models.Index(
                        fields=["product_number"], name="products_product_77e2e3_idx"
                    ),
                    models.Index(fields=["status"], name="products_status_a30e64_idx"),
                    models.Index(
                        fields=["created_at"], name="products_created_e1ba5f_idx"
                    ),
                ],
            },
        ),
    ]
