# Generated by Django 5.2.7 on 2025-11-04 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="company_name",
            field=models.CharField(
                help_text="例: 株式会社ABC",
                max_length=200,
                unique=True,
                verbose_name="企業名",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_code",
            field=models.CharField(
                help_text="例: SUP001",
                max_length=50,
                unique=True,
                verbose_name="サプライヤーコード",
            ),
        ),
        migrations.AlterField(
            model_name="supplierbranch",
            name="branch_code",
            field=models.CharField(
                help_text="例: SUP001-HQ(本社), SUP001-NAG(名古屋支店)",
                max_length=50,
                unique=True,
                verbose_name="拠点コード",
            ),
        ),
        migrations.AlterField(
            model_name="supplierbranch",
            name="branch_name",
            field=models.CharField(
                help_text="例: 本社、名古屋支店, 安城営業所",
                max_length=200,
                verbose_name="拠点名",
            ),
        ),
        migrations.AlterField(
            model_name="suppliercontact",
            name="name_kana",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="担当者名(カナ)"
            ),
        ),
        migrations.AlterField(
            model_name="suppliercontact",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="電話番号は数字、ハイフン、プラス記号、括弧のみ使用可能です",
                        regex="^[0-9\\-\\+\\(\\)]+$",
                    )
                ],
                verbose_name="電話番号(直通)",
            ),
        ),
    ]
