# Generated by Django 5.2.7 on 2025-11-03 12:36

import api.purchases.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("supplier", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_number",
                    models.CharField(
                        help_text="部品を識別する品番",
                        max_length=100,
                        verbose_name="部品品番",
                    ),
                ),
                ("part_name", models.CharField(max_length=200, verbose_name="部品名")),
                (
                    "specification",
                    models.TextField(
                        blank=True, help_text="部品の詳細仕様", verbose_name="仕様"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="個",
                        help_text="発注単位（個、kg、m等）",
                        max_length=20,
                        verbose_name="単位",
                    ),
                ),
                (
                    "minimum_order_quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="最小発注ロット数",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="最小発注数量",
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="標準納期日数",
                        null=True,
                        verbose_name="リードタイム（日）",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="この部品が現在使用可能かどうか",
                        verbose_name="有効",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_parts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="この部品が使用される製品",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="products.product",
                        verbose_name="製品",
                    ),
                ),
                (
                    "supplier_branch",
                    models.ForeignKey(
                        help_text="この部品を供給する仕入先支店",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parts",
                        to="supplier.supplierbranch",
                        verbose_name="仕入先支店",
                    ),
                ),
            ],
            options={
                "verbose_name": "部品",
                "verbose_name_plural": "部品一覧",
                "db_table": "parts",
                "ordering": ["part_number"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="税抜単価",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="単価",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="この価格が有効になる日", verbose_name="開始日"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="この価格が無効になる日（空白の場合は無期限）",
                        null=True,
                        verbose_name="終了日",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="手動で無効化する場合に使用",
                        verbose_name="有効",
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True,
                        help_text="価格変更の理由や背景",
                        verbose_name="変更理由",
                    ),
                ),
                (
                    "quote_file",
                    models.FileField(
                        blank=True,
                        help_text="見積書のPDFやExcelファイル",
                        max_length=500,
                        null=True,
                        upload_to=api.purchases.models.quote_file_upload_path,
                        verbose_name="見積書ファイル",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_price_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_histories",
                        to="purchases.part",
                        verbose_name="部品",
                    ),
                ),
            ],
            options={
                "verbose_name": "価格履歴",
                "verbose_name_plural": "価格履歴一覧",
                "db_table": "price_histories",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(fields=["part_number"], name="parts_part_nu_af7709_idx"),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["product", "is_active"], name="parts_product_b900d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(
                fields=["supplier_branch", "is_active"], name="parts_supplie_0e0895_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="part",
            index=models.Index(fields=["created_at"], name="parts_created_c64329_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="part",
            unique_together={("product", "supplier_branch", "part_number")},
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["part", "start_date"], name="price_histo_part_id_e309bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["part", "is_active"], name="price_histo_part_id_9d6b7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["start_date", "end_date"], name="price_histo_start_d_5da699_idx"
            ),
        ),
    ]
