# Generated by Django 5.2.7 on 2025-11-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="lead_time_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="標準納期日数",
                null=True,
                verbose_name="リードタイム(日)",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="unit",
            field=models.CharField(
                default="個",
                help_text="発注単位(個、kg、m等)",
                max_length=20,
                verbose_name="単位",
            ),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="この価格が無効になる日(空白の場合は無期限)",
                null=True,
                verbose_name="終了日",
            ),
        ),
    ]
